// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: select.proto

package tipb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	github_com_pingcap_tipb_sharedbytes "github.com/pingcap/tipb/sharedbytes"

	io "io"

	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EncodeType int32

const (
	EncodeType_TypeDefault EncodeType = 0
	EncodeType_TypeChunk   EncodeType = 1
	// TypeCHBlock is used by TiSpark and TiFlash, in this encode mode, TiFlash will encode the data using native ch block format
	EncodeType_TypeCHBlock EncodeType = 2
)

var EncodeType_name = map[int32]string{
	0: "TypeDefault",
	1: "TypeChunk",
	2: "TypeCHBlock",
}
var EncodeType_value = map[string]int32{
	"TypeDefault": 0,
	"TypeChunk":   1,
	"TypeCHBlock": 2,
}

func (x EncodeType) Enum() *EncodeType {
	p := new(EncodeType)
	*p = x
	return p
}
func (x EncodeType) String() string {
	return proto.EnumName(EncodeType_name, int32(x))
}
func (x *EncodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EncodeType_value, data, "EncodeType")
	if err != nil {
		return err
	}
	*x = EncodeType(value)
	return nil
}
func (EncodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptorSelect, []int{0} }

type Endian int32

const (
	Endian_LittleEndian Endian = 0
	Endian_BigEndian    Endian = 1
)

var Endian_name = map[int32]string{
	0: "LittleEndian",
	1: "BigEndian",
}
var Endian_value = map[string]int32{
	"LittleEndian": 0,
	"BigEndian":    1,
}

func (x Endian) Enum() *Endian {
	p := new(Endian)
	*p = x
	return p
}
func (x Endian) String() string {
	return proto.EnumName(Endian_name, int32(x))
}
func (x *Endian) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Endian_value, data, "Endian")
	if err != nil {
		return err
	}
	*x = Endian(value)
	return nil
}
func (Endian) EnumDescriptor() ([]byte, []int) { return fileDescriptorSelect, []int{1} }

// values are all in text format.
type Row struct {
	Handle           []byte `protobuf:"bytes,1,opt,name=handle" json:"handle,omitempty"`
	Data             []byte `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{0} }

func (m *Row) GetHandle() []byte {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *Row) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error struct {
	Code             int32  `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg              string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{1} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// It is the data of a intermidiate output channel
type IntermediateOutput struct {
	EncodeType       EncodeType `protobuf:"varint,1,opt,name=encode_type,json=encodeType,enum=tipb.EncodeType" json:"encode_type"`
	Chunks           []Chunk    `protobuf:"bytes,2,rep,name=chunks" json:"chunks"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *IntermediateOutput) Reset()                    { *m = IntermediateOutput{} }
func (m *IntermediateOutput) String() string            { return proto.CompactTextString(m) }
func (*IntermediateOutput) ProtoMessage()               {}
func (*IntermediateOutput) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{2} }

func (m *IntermediateOutput) GetEncodeType() EncodeType {
	if m != nil {
		return m.EncodeType
	}
	return EncodeType_TypeDefault
}

func (m *IntermediateOutput) GetChunks() []Chunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

// Response for SelectRequest.
type SelectResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	// Result rows.
	Rows []*Row `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	// Use multiple chunks to reduce memory allocation and
	// avoid allocating large contiguous memory.
	Chunks       []Chunk  `protobuf:"bytes,3,rep,name=chunks" json:"chunks"`
	Warnings     []*Error `protobuf:"bytes,4,rep,name=warnings" json:"warnings,omitempty"`
	OutputCounts []int64  `protobuf:"varint,5,rep,name=output_counts,json=outputCounts" json:"output_counts,omitempty"`
	WarningCount *int64   `protobuf:"varint,6,opt,name=warning_count,json=warningCount" json:"warning_count,omitempty"`
	// The execution summary of each executor, in the order in request.
	ExecutionSummaries []*ExecutorExecutionSummary `protobuf:"bytes,8,rep,name=execution_summaries,json=executionSummaries" json:"execution_summaries,omitempty"`
	// It indicates the encode type of response.
	EncodeType EncodeType `protobuf:"varint,9,opt,name=encode_type,json=encodeType,enum=tipb.EncodeType" json:"encode_type"`
	// ndvs collects the number of distinct value information per range. It will be used to serve as execution feedback information.
	// Helping us improve the table's statistics information.
	Ndvs []int64 `protobuf:"varint,10,rep,name=ndvs" json:"ndvs,omitempty"`
	// It contains all the intermedidate outputs.
	IntermediateOutputs []*IntermediateOutput `protobuf:"bytes,11,rep,name=intermediate_outputs,json=intermediateOutputs" json:"intermediate_outputs,omitempty"`
	XXX_unrecognized    []byte                `json:"-"`
}

func (m *SelectResponse) Reset()                    { *m = SelectResponse{} }
func (m *SelectResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()               {}
func (*SelectResponse) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{3} }

func (m *SelectResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SelectResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *SelectResponse) GetChunks() []Chunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *SelectResponse) GetWarnings() []*Error {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *SelectResponse) GetOutputCounts() []int64 {
	if m != nil {
		return m.OutputCounts
	}
	return nil
}

func (m *SelectResponse) GetWarningCount() int64 {
	if m != nil && m.WarningCount != nil {
		return *m.WarningCount
	}
	return 0
}

func (m *SelectResponse) GetExecutionSummaries() []*ExecutorExecutionSummary {
	if m != nil {
		return m.ExecutionSummaries
	}
	return nil
}

func (m *SelectResponse) GetEncodeType() EncodeType {
	if m != nil {
		return m.EncodeType
	}
	return EncodeType_TypeDefault
}

func (m *SelectResponse) GetNdvs() []int64 {
	if m != nil {
		return m.Ndvs
	}
	return nil
}

func (m *SelectResponse) GetIntermediateOutputs() []*IntermediateOutput {
	if m != nil {
		return m.IntermediateOutputs
	}
	return nil
}

// Chunk contains multiple rows data and rows meta.
type Chunk struct {
	// Data for all rows in the chunk.
	RowsData github_com_pingcap_tipb_sharedbytes.SharedBytes `protobuf:"bytes,3,opt,name=rows_data,json=rowsData,customtype=github.com/pingcap/tipb/sharedbytes.SharedBytes" json:"rows_data"`
	// Meta data for every row.
	RowsMeta         []RowMeta `protobuf:"bytes,4,rep,name=rows_meta,json=rowsMeta" json:"rows_meta"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{4} }

func (m *Chunk) GetRowsMeta() []RowMeta {
	if m != nil {
		return m.RowsMeta
	}
	return nil
}

// IntermediateOutputChannel is the channel description for the intermediate ouput.
// The SelectResponse of a DAGRequest may output some intermediate data because not all rows can be processed in DAG.
// For example, the executor IndexLookUp scans the index records and look up the rows locally.
// If a related row of a index is not found locally, this index record should be ouput into the intermediate channel
// for the further processment in the TiDB side.
type IntermediateOutputChannel struct {
	// executor_idx indicates which executor outputs this intermediate result.
	ExecutorIdx uint32 `protobuf:"varint,1,req,name=executor_idx,json=executorIdx" json:"executor_idx"`
	// It represents which columns we should output.
	OutputOffsets    []uint32 `protobuf:"varint,2,rep,name=output_offsets,json=outputOffsets" json:"output_offsets,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IntermediateOutputChannel) Reset()                    { *m = IntermediateOutputChannel{} }
func (m *IntermediateOutputChannel) String() string            { return proto.CompactTextString(m) }
func (*IntermediateOutputChannel) ProtoMessage()               {}
func (*IntermediateOutputChannel) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{5} }

func (m *IntermediateOutputChannel) GetExecutorIdx() uint32 {
	if m != nil {
		return m.ExecutorIdx
	}
	return 0
}

func (m *IntermediateOutputChannel) GetOutputOffsets() []uint32 {
	if m != nil {
		return m.OutputOffsets
	}
	return nil
}

// RowMeta contains row handle and length of a row.
type RowMeta struct {
	Handle           int64  `protobuf:"varint,1,opt,name=handle" json:"handle"`
	Length           int64  `protobuf:"varint,2,opt,name=length" json:"length"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RowMeta) Reset()                    { *m = RowMeta{} }
func (m *RowMeta) String() string            { return proto.CompactTextString(m) }
func (*RowMeta) ProtoMessage()               {}
func (*RowMeta) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{6} }

func (m *RowMeta) GetHandle() int64 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *RowMeta) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

// DAGRequest represents the request that will be handled with DAG mode.
type DAGRequest struct {
	// Transaction start timestamp.
	// Deprecated. Start Ts has been moved to coprocessor.Request.
	StartTsFallback *uint64 `protobuf:"varint,1,opt,name=start_ts_fallback,json=startTsFallback" json:"start_ts_fallback,omitempty"`
	// It represents push down Executors and follows the order of depth-first search with post-order traversal.
	// That is: left child first, then right child, then parent.
	// For example, a DAG:
	//                A
	//               /
	//              B
	//            /   \
	//           C     D
	//          /     / \
	//         E     F   G
	//        /
	//       H
	// Its order should be: [H, E, C, F, G, D, B, A]
	// In most cases, there is only one child for each parent, that makes executors simple array from the srouce
	// to the out most executors, and the response only need to output the final rows.
	// But when a executor has more than one children, for example, IndexLookUp, some intermedidate result is required to output.
	// The field `intermediate_output_channels` describes it.
	Executors []*Executor `protobuf:"bytes,2,rep,name=executors" json:"executors,omitempty"`
	// time zone offset in seconds
	TimeZoneOffset int64 `protobuf:"varint,3,opt,name=time_zone_offset,json=timeZoneOffset" json:"time_zone_offset"`
	// flags are used to store flags that change the execution mode, it contains:
	// 	ignore_truncate = 1
	// 		truncate error should be ignore if set.
	// 	truncate_as_warning = 1 << 1
	// 		when ignored_truncate is not set, return warning instead of error if this flag is set.
	// 	...
	// 	add more when needed.
	Flags uint64 `protobuf:"varint,4,opt,name=flags" json:"flags"`
	// It represents which columns we should output.
	OutputOffsets []uint32 `protobuf:"varint,5,rep,name=output_offsets,json=outputOffsets" json:"output_offsets,omitempty"`
	// It represents whether we collect the detailed scan counts in each range.
	CollectRangeCounts *bool `protobuf:"varint,6,opt,name=collect_range_counts,json=collectRangeCounts" json:"collect_range_counts,omitempty"`
	// It indicates the maximum number of warning,
	// which is the number of messages that SHOW WARNINGS displays.
	MaxWarningCount *uint64 `protobuf:"varint,7,opt,name=max_warning_count,json=maxWarningCount" json:"max_warning_count,omitempty"`
	// It indicates the encode type of response.
	EncodeType EncodeType `protobuf:"varint,8,opt,name=encode_type,json=encodeType,enum=tipb.EncodeType" json:"encode_type"`
	// It indicates the sql_mode.
	SqlMode *uint64 `protobuf:"varint,9,opt,name=sql_mode,json=sqlMode" json:"sql_mode,omitempty"`
	// supply offset is not enough since we have daylight saving time present in some regions
	TimeZoneName string `protobuf:"bytes,11,opt,name=time_zone_name,json=timeZoneName" json:"time_zone_name"`
	// It represents whether or not TiKV should collect execution summaries.
	// Execution summaries will be collected into `execution_summaries` field
	// in the response.
	CollectExecutionSummaries *bool `protobuf:"varint,12,opt,name=collect_execution_summaries,json=collectExecutionSummaries" json:"collect_execution_summaries,omitempty"`
	// Represents the maximum size of one packet, any generated string, or any parameter sent as long data.
	MaxAllowedPacket *uint64 `protobuf:"varint,13,opt,name=max_allowed_packet,json=maxAllowedPacket" json:"max_allowed_packet,omitempty"`
	// Represents the chunk memory layout.
	ChunkMemoryLayout *ChunkMemoryLayout `protobuf:"bytes,14,opt,name=chunk_memory_layout,json=chunkMemoryLayout" json:"chunk_memory_layout,omitempty"`
	// Represents whether the expression use RPN form.
	IsRpnExpr *bool `protobuf:"varint,15,opt,name=is_rpn_expr,json=isRpnExpr" json:"is_rpn_expr,omitempty"`
	// UserIdentity uses to do privilege check. It is only used in TiDB cluster memory table.
	User *UserIdentity `protobuf:"bytes,16,opt,name=user" json:"user,omitempty"`
	// Represents tree struct based executors, if this field is set, should ignore the executors field, currently only used in TiFlash
	RootExecutor *Executor `protobuf:"bytes,17,opt,name=root_executor,json=rootExecutor" json:"root_executor,omitempty"`
	// Force using the encode type specified by encode_type, currently only used in TiFlash
	ForceEncodeType *bool `protobuf:"varint,18,opt,name=force_encode_type,json=forceEncodeType" json:"force_encode_type,omitempty"`
	// It indicates the number of digits by which to increase the scale of the result of division operations performed with the / operator.
	DivPrecisionIncrement *uint32 `protobuf:"varint,19,opt,name=div_precision_increment,json=divPrecisionIncrement" json:"div_precision_increment,omitempty"`
	// It inidcates the intermdidate result channels.
	IntermediateOutputChannels []*IntermediateOutputChannel `protobuf:"bytes,20,rep,name=intermediate_output_channels,json=intermediateOutputChannels" json:"intermediate_output_channels,omitempty"`
	XXX_unrecognized           []byte                       `json:"-"`
}

func (m *DAGRequest) Reset()                    { *m = DAGRequest{} }
func (m *DAGRequest) String() string            { return proto.CompactTextString(m) }
func (*DAGRequest) ProtoMessage()               {}
func (*DAGRequest) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{7} }

func (m *DAGRequest) GetStartTsFallback() uint64 {
	if m != nil && m.StartTsFallback != nil {
		return *m.StartTsFallback
	}
	return 0
}

func (m *DAGRequest) GetExecutors() []*Executor {
	if m != nil {
		return m.Executors
	}
	return nil
}

func (m *DAGRequest) GetTimeZoneOffset() int64 {
	if m != nil {
		return m.TimeZoneOffset
	}
	return 0
}

func (m *DAGRequest) GetFlags() uint64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *DAGRequest) GetOutputOffsets() []uint32 {
	if m != nil {
		return m.OutputOffsets
	}
	return nil
}

func (m *DAGRequest) GetCollectRangeCounts() bool {
	if m != nil && m.CollectRangeCounts != nil {
		return *m.CollectRangeCounts
	}
	return false
}

func (m *DAGRequest) GetMaxWarningCount() uint64 {
	if m != nil && m.MaxWarningCount != nil {
		return *m.MaxWarningCount
	}
	return 0
}

func (m *DAGRequest) GetEncodeType() EncodeType {
	if m != nil {
		return m.EncodeType
	}
	return EncodeType_TypeDefault
}

func (m *DAGRequest) GetSqlMode() uint64 {
	if m != nil && m.SqlMode != nil {
		return *m.SqlMode
	}
	return 0
}

func (m *DAGRequest) GetTimeZoneName() string {
	if m != nil {
		return m.TimeZoneName
	}
	return ""
}

func (m *DAGRequest) GetCollectExecutionSummaries() bool {
	if m != nil && m.CollectExecutionSummaries != nil {
		return *m.CollectExecutionSummaries
	}
	return false
}

func (m *DAGRequest) GetMaxAllowedPacket() uint64 {
	if m != nil && m.MaxAllowedPacket != nil {
		return *m.MaxAllowedPacket
	}
	return 0
}

func (m *DAGRequest) GetChunkMemoryLayout() *ChunkMemoryLayout {
	if m != nil {
		return m.ChunkMemoryLayout
	}
	return nil
}

func (m *DAGRequest) GetIsRpnExpr() bool {
	if m != nil && m.IsRpnExpr != nil {
		return *m.IsRpnExpr
	}
	return false
}

func (m *DAGRequest) GetUser() *UserIdentity {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DAGRequest) GetRootExecutor() *Executor {
	if m != nil {
		return m.RootExecutor
	}
	return nil
}

func (m *DAGRequest) GetForceEncodeType() bool {
	if m != nil && m.ForceEncodeType != nil {
		return *m.ForceEncodeType
	}
	return false
}

func (m *DAGRequest) GetDivPrecisionIncrement() uint32 {
	if m != nil && m.DivPrecisionIncrement != nil {
		return *m.DivPrecisionIncrement
	}
	return 0
}

func (m *DAGRequest) GetIntermediateOutputChannels() []*IntermediateOutputChannel {
	if m != nil {
		return m.IntermediateOutputChannels
	}
	return nil
}

type ChunkMemoryLayout struct {
	// Represents the endian.
	Endian           Endian `protobuf:"varint,1,opt,name=endian,enum=tipb.Endian" json:"endian"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChunkMemoryLayout) Reset()                    { *m = ChunkMemoryLayout{} }
func (m *ChunkMemoryLayout) String() string            { return proto.CompactTextString(m) }
func (*ChunkMemoryLayout) ProtoMessage()               {}
func (*ChunkMemoryLayout) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{8} }

func (m *ChunkMemoryLayout) GetEndian() Endian {
	if m != nil {
		return m.Endian
	}
	return Endian_LittleEndian
}

type UserIdentity struct {
	UserName         string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name"`
	UserHost         string `protobuf:"bytes,2,opt,name=user_host,json=userHost" json:"user_host"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UserIdentity) Reset()                    { *m = UserIdentity{} }
func (m *UserIdentity) String() string            { return proto.CompactTextString(m) }
func (*UserIdentity) ProtoMessage()               {}
func (*UserIdentity) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{9} }

func (m *UserIdentity) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserIdentity) GetUserHost() string {
	if m != nil {
		return m.UserHost
	}
	return ""
}

type StreamResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	// Data for all rows
	Data     github_com_pingcap_tipb_sharedbytes.SharedBytes `protobuf:"bytes,3,opt,name=data,customtype=github.com/pingcap/tipb/sharedbytes.SharedBytes" json:"data"`
	Warnings []*Error                                        `protobuf:"bytes,4,rep,name=warnings" json:"warnings,omitempty"`
	// output row count for each executor
	OutputCounts     []int64 `protobuf:"varint,5,rep,name=output_counts,json=outputCounts" json:"output_counts,omitempty"`
	WarningCount     *int64  `protobuf:"varint,6,opt,name=warning_count,json=warningCount" json:"warning_count,omitempty"`
	Ndvs             []int64 `protobuf:"varint,7,rep,name=ndvs" json:"ndvs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StreamResponse) Reset()                    { *m = StreamResponse{} }
func (m *StreamResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()               {}
func (*StreamResponse) Descriptor() ([]byte, []int) { return fileDescriptorSelect, []int{10} }

func (m *StreamResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *StreamResponse) GetWarnings() []*Error {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *StreamResponse) GetOutputCounts() []int64 {
	if m != nil {
		return m.OutputCounts
	}
	return nil
}

func (m *StreamResponse) GetWarningCount() int64 {
	if m != nil && m.WarningCount != nil {
		return *m.WarningCount
	}
	return 0
}

func (m *StreamResponse) GetNdvs() []int64 {
	if m != nil {
		return m.Ndvs
	}
	return nil
}

func init() {
	proto.RegisterType((*Row)(nil), "tipb.Row")
	proto.RegisterType((*Error)(nil), "tipb.Error")
	proto.RegisterType((*IntermediateOutput)(nil), "tipb.IntermediateOutput")
	proto.RegisterType((*SelectResponse)(nil), "tipb.SelectResponse")
	proto.RegisterType((*Chunk)(nil), "tipb.Chunk")
	proto.RegisterType((*IntermediateOutputChannel)(nil), "tipb.IntermediateOutputChannel")
	proto.RegisterType((*RowMeta)(nil), "tipb.RowMeta")
	proto.RegisterType((*DAGRequest)(nil), "tipb.DAGRequest")
	proto.RegisterType((*ChunkMemoryLayout)(nil), "tipb.ChunkMemoryLayout")
	proto.RegisterType((*UserIdentity)(nil), "tipb.UserIdentity")
	proto.RegisterType((*StreamResponse)(nil), "tipb.StreamResponse")
	proto.RegisterEnum("tipb.EncodeType", EncodeType_name, EncodeType_value)
	proto.RegisterEnum("tipb.Endian", Endian_name, Endian_value)
}
func (m *Row) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Row) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Handle != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSelect(dAtA, i, uint64(len(m.Handle)))
		i += copy(dAtA[i:], m.Handle)
	}
	if m.Data != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSelect(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.Code))
	dAtA[i] = 0x12
	i++
	i = encodeVarintSelect(dAtA, i, uint64(len(m.Msg)))
	i += copy(dAtA[i:], m.Msg)
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *IntermediateOutput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IntermediateOutput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.EncodeType))
	if len(m.Chunks) > 0 {
		for _, msg := range m.Chunks {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SelectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SelectResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSelect(dAtA, i, uint64(m.Error.Size()))
		n1, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Rows) > 0 {
		for _, msg := range m.Rows {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Chunks) > 0 {
		for _, msg := range m.Chunks {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Warnings) > 0 {
		for _, msg := range m.Warnings {
			dAtA[i] = 0x22
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.OutputCounts) > 0 {
		for _, num := range m.OutputCounts {
			dAtA[i] = 0x28
			i++
			i = encodeVarintSelect(dAtA, i, uint64(num))
		}
	}
	if m.WarningCount != nil {
		dAtA[i] = 0x30
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.WarningCount))
	}
	if len(m.ExecutionSummaries) > 0 {
		for _, msg := range m.ExecutionSummaries {
			dAtA[i] = 0x42
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x48
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.EncodeType))
	if len(m.Ndvs) > 0 {
		for _, num := range m.Ndvs {
			dAtA[i] = 0x50
			i++
			i = encodeVarintSelect(dAtA, i, uint64(num))
		}
	}
	if len(m.IntermediateOutputs) > 0 {
		for _, msg := range m.IntermediateOutputs {
			dAtA[i] = 0x5a
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Chunk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chunk) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x1a
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.RowsData.Size()))
	n2, err := m.RowsData.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.RowsMeta) > 0 {
		for _, msg := range m.RowsMeta {
			dAtA[i] = 0x22
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *IntermediateOutputChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IntermediateOutputChannel) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.ExecutorIdx))
	if len(m.OutputOffsets) > 0 {
		for _, num := range m.OutputOffsets {
			dAtA[i] = 0x10
			i++
			i = encodeVarintSelect(dAtA, i, uint64(num))
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RowMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RowMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.Handle))
	dAtA[i] = 0x10
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.Length))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DAGRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DAGRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StartTsFallback != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.StartTsFallback))
	}
	if len(m.Executors) > 0 {
		for _, msg := range m.Executors {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x18
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.TimeZoneOffset))
	dAtA[i] = 0x20
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.Flags))
	if len(m.OutputOffsets) > 0 {
		for _, num := range m.OutputOffsets {
			dAtA[i] = 0x28
			i++
			i = encodeVarintSelect(dAtA, i, uint64(num))
		}
	}
	if m.CollectRangeCounts != nil {
		dAtA[i] = 0x30
		i++
		if *m.CollectRangeCounts {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.MaxWarningCount != nil {
		dAtA[i] = 0x38
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.MaxWarningCount))
	}
	dAtA[i] = 0x40
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.EncodeType))
	if m.SqlMode != nil {
		dAtA[i] = 0x48
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.SqlMode))
	}
	dAtA[i] = 0x5a
	i++
	i = encodeVarintSelect(dAtA, i, uint64(len(m.TimeZoneName)))
	i += copy(dAtA[i:], m.TimeZoneName)
	if m.CollectExecutionSummaries != nil {
		dAtA[i] = 0x60
		i++
		if *m.CollectExecutionSummaries {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.MaxAllowedPacket != nil {
		dAtA[i] = 0x68
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.MaxAllowedPacket))
	}
	if m.ChunkMemoryLayout != nil {
		dAtA[i] = 0x72
		i++
		i = encodeVarintSelect(dAtA, i, uint64(m.ChunkMemoryLayout.Size()))
		n3, err := m.ChunkMemoryLayout.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.IsRpnExpr != nil {
		dAtA[i] = 0x78
		i++
		if *m.IsRpnExpr {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.User != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSelect(dAtA, i, uint64(m.User.Size()))
		n4, err := m.User.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.RootExecutor != nil {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSelect(dAtA, i, uint64(m.RootExecutor.Size()))
		n5, err := m.RootExecutor.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.ForceEncodeType != nil {
		dAtA[i] = 0x90
		i++
		dAtA[i] = 0x1
		i++
		if *m.ForceEncodeType {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.DivPrecisionIncrement != nil {
		dAtA[i] = 0x98
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.DivPrecisionIncrement))
	}
	if len(m.IntermediateOutputChannels) > 0 {
		for _, msg := range m.IntermediateOutputChannels {
			dAtA[i] = 0xa2
			i++
			dAtA[i] = 0x1
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ChunkMemoryLayout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChunkMemoryLayout) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.Endian))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UserIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserIdentity) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintSelect(dAtA, i, uint64(len(m.UserName)))
	i += copy(dAtA[i:], m.UserName)
	dAtA[i] = 0x12
	i++
	i = encodeVarintSelect(dAtA, i, uint64(len(m.UserHost)))
	i += copy(dAtA[i:], m.UserHost)
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *StreamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSelect(dAtA, i, uint64(m.Error.Size()))
		n6, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	dAtA[i] = 0x1a
	i++
	i = encodeVarintSelect(dAtA, i, uint64(m.Data.Size()))
	n7, err := m.Data.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	if len(m.Warnings) > 0 {
		for _, msg := range m.Warnings {
			dAtA[i] = 0x22
			i++
			i = encodeVarintSelect(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.OutputCounts) > 0 {
		for _, num := range m.OutputCounts {
			dAtA[i] = 0x28
			i++
			i = encodeVarintSelect(dAtA, i, uint64(num))
		}
	}
	if m.WarningCount != nil {
		dAtA[i] = 0x30
		i++
		i = encodeVarintSelect(dAtA, i, uint64(*m.WarningCount))
	}
	if len(m.Ndvs) > 0 {
		for _, num := range m.Ndvs {
			dAtA[i] = 0x38
			i++
			i = encodeVarintSelect(dAtA, i, uint64(num))
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintSelect(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Row) Size() (n int) {
	var l int
	_ = l
	if m.Handle != nil {
		l = len(m.Handle)
		n += 1 + l + sovSelect(uint64(l))
	}
	if m.Data != nil {
		l = len(m.Data)
		n += 1 + l + sovSelect(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Error) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovSelect(uint64(m.Code))
	l = len(m.Msg)
	n += 1 + l + sovSelect(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *IntermediateOutput) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovSelect(uint64(m.EncodeType))
	if len(m.Chunks) > 0 {
		for _, e := range m.Chunks {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SelectResponse) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovSelect(uint64(l))
	}
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if len(m.Chunks) > 0 {
		for _, e := range m.Chunks {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if len(m.Warnings) > 0 {
		for _, e := range m.Warnings {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if len(m.OutputCounts) > 0 {
		for _, e := range m.OutputCounts {
			n += 1 + sovSelect(uint64(e))
		}
	}
	if m.WarningCount != nil {
		n += 1 + sovSelect(uint64(*m.WarningCount))
	}
	if len(m.ExecutionSummaries) > 0 {
		for _, e := range m.ExecutionSummaries {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	n += 1 + sovSelect(uint64(m.EncodeType))
	if len(m.Ndvs) > 0 {
		for _, e := range m.Ndvs {
			n += 1 + sovSelect(uint64(e))
		}
	}
	if len(m.IntermediateOutputs) > 0 {
		for _, e := range m.IntermediateOutputs {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Chunk) Size() (n int) {
	var l int
	_ = l
	l = m.RowsData.Size()
	n += 1 + l + sovSelect(uint64(l))
	if len(m.RowsMeta) > 0 {
		for _, e := range m.RowsMeta {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *IntermediateOutputChannel) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovSelect(uint64(m.ExecutorIdx))
	if len(m.OutputOffsets) > 0 {
		for _, e := range m.OutputOffsets {
			n += 1 + sovSelect(uint64(e))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RowMeta) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovSelect(uint64(m.Handle))
	n += 1 + sovSelect(uint64(m.Length))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DAGRequest) Size() (n int) {
	var l int
	_ = l
	if m.StartTsFallback != nil {
		n += 1 + sovSelect(uint64(*m.StartTsFallback))
	}
	if len(m.Executors) > 0 {
		for _, e := range m.Executors {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	n += 1 + sovSelect(uint64(m.TimeZoneOffset))
	n += 1 + sovSelect(uint64(m.Flags))
	if len(m.OutputOffsets) > 0 {
		for _, e := range m.OutputOffsets {
			n += 1 + sovSelect(uint64(e))
		}
	}
	if m.CollectRangeCounts != nil {
		n += 2
	}
	if m.MaxWarningCount != nil {
		n += 1 + sovSelect(uint64(*m.MaxWarningCount))
	}
	n += 1 + sovSelect(uint64(m.EncodeType))
	if m.SqlMode != nil {
		n += 1 + sovSelect(uint64(*m.SqlMode))
	}
	l = len(m.TimeZoneName)
	n += 1 + l + sovSelect(uint64(l))
	if m.CollectExecutionSummaries != nil {
		n += 2
	}
	if m.MaxAllowedPacket != nil {
		n += 1 + sovSelect(uint64(*m.MaxAllowedPacket))
	}
	if m.ChunkMemoryLayout != nil {
		l = m.ChunkMemoryLayout.Size()
		n += 1 + l + sovSelect(uint64(l))
	}
	if m.IsRpnExpr != nil {
		n += 2
	}
	if m.User != nil {
		l = m.User.Size()
		n += 2 + l + sovSelect(uint64(l))
	}
	if m.RootExecutor != nil {
		l = m.RootExecutor.Size()
		n += 2 + l + sovSelect(uint64(l))
	}
	if m.ForceEncodeType != nil {
		n += 3
	}
	if m.DivPrecisionIncrement != nil {
		n += 2 + sovSelect(uint64(*m.DivPrecisionIncrement))
	}
	if len(m.IntermediateOutputChannels) > 0 {
		for _, e := range m.IntermediateOutputChannels {
			l = e.Size()
			n += 2 + l + sovSelect(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ChunkMemoryLayout) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovSelect(uint64(m.Endian))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UserIdentity) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserName)
	n += 1 + l + sovSelect(uint64(l))
	l = len(m.UserHost)
	n += 1 + l + sovSelect(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StreamResponse) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovSelect(uint64(l))
	}
	l = m.Data.Size()
	n += 1 + l + sovSelect(uint64(l))
	if len(m.Warnings) > 0 {
		for _, e := range m.Warnings {
			l = e.Size()
			n += 1 + l + sovSelect(uint64(l))
		}
	}
	if len(m.OutputCounts) > 0 {
		for _, e := range m.OutputCounts {
			n += 1 + sovSelect(uint64(e))
		}
	}
	if m.WarningCount != nil {
		n += 1 + sovSelect(uint64(*m.WarningCount))
	}
	if len(m.Ndvs) > 0 {
		for _, e := range m.Ndvs {
			n += 1 + sovSelect(uint64(e))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSelect(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSelect(x uint64) (n int) {
	return sovSelect(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Row) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Row: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Row: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handle", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Handle = append(m.Handle[:0], dAtA[iNdEx:postIndex]...)
			if m.Handle == nil {
				m.Handle = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IntermediateOutput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IntermediateOutput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IntermediateOutput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodeType", wireType)
			}
			m.EncodeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodeType |= (EncodeType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chunks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chunks = append(m.Chunks, Chunk{})
			if err := m.Chunks[len(m.Chunks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SelectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SelectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SelectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, &Row{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chunks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chunks = append(m.Chunks, Chunk{})
			if err := m.Chunks[len(m.Chunks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warnings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Warnings = append(m.Warnings, &Error{})
			if err := m.Warnings[len(m.Warnings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OutputCounts = append(m.OutputCounts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSelect
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSelect
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OutputCounts = append(m.OutputCounts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCounts", wireType)
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WarningCount", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WarningCount = &v
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionSummaries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutionSummaries = append(m.ExecutionSummaries, &ExecutorExecutionSummary{})
			if err := m.ExecutionSummaries[len(m.ExecutionSummaries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodeType", wireType)
			}
			m.EncodeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodeType |= (EncodeType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Ndvs = append(m.Ndvs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSelect
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSelect
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Ndvs = append(m.Ndvs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Ndvs", wireType)
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntermediateOutputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IntermediateOutputs = append(m.IntermediateOutputs, &IntermediateOutput{})
			if err := m.IntermediateOutputs[len(m.IntermediateOutputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Chunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RowsData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RowsMeta = append(m.RowsMeta, RowMeta{})
			if err := m.RowsMeta[len(m.RowsMeta)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IntermediateOutputChannel) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IntermediateOutputChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IntermediateOutputChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutorIdx", wireType)
			}
			m.ExecutorIdx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutorIdx |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OutputOffsets = append(m.OutputOffsets, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSelect
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSelect
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OutputOffsets = append(m.OutputOffsets, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputOffsets", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RowMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RowMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RowMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handle", wireType)
			}
			m.Handle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Handle |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			m.Length = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Length |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DAGRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DAGRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DAGRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTsFallback", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StartTsFallback = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executors = append(m.Executors, &Executor{})
			if err := m.Executors[len(m.Executors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeZoneOffset", wireType)
			}
			m.TimeZoneOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeZoneOffset |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OutputOffsets = append(m.OutputOffsets, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSelect
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSelect
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OutputOffsets = append(m.OutputOffsets, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputOffsets", wireType)
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectRangeCounts", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.CollectRangeCounts = &b
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWarningCount", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxWarningCount = &v
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncodeType", wireType)
			}
			m.EncodeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EncodeType |= (EncodeType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SqlMode", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SqlMode = &v
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeZoneName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectExecutionSummaries", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.CollectExecutionSummaries = &b
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAllowedPacket", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxAllowedPacket = &v
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChunkMemoryLayout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChunkMemoryLayout == nil {
				m.ChunkMemoryLayout = &ChunkMemoryLayout{}
			}
			if err := m.ChunkMemoryLayout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRpnExpr", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.IsRpnExpr = &b
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.User == nil {
				m.User = &UserIdentity{}
			}
			if err := m.User.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootExecutor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RootExecutor == nil {
				m.RootExecutor = &Executor{}
			}
			if err := m.RootExecutor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForceEncodeType", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ForceEncodeType = &b
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DivPrecisionIncrement", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DivPrecisionIncrement = &v
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntermediateOutputChannels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IntermediateOutputChannels = append(m.IntermediateOutputChannels, &IntermediateOutputChannel{})
			if err := m.IntermediateOutputChannels[len(m.IntermediateOutputChannels)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChunkMemoryLayout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChunkMemoryLayout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChunkMemoryLayout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endian", wireType)
			}
			m.Endian = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Endian |= (Endian(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserHost", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserHost = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warnings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelect
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Warnings = append(m.Warnings, &Error{})
			if err := m.Warnings[len(m.Warnings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OutputCounts = append(m.OutputCounts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSelect
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSelect
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OutputCounts = append(m.OutputCounts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCounts", wireType)
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WarningCount", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WarningCount = &v
		case 7:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Ndvs = append(m.Ndvs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSelect
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSelect
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Ndvs = append(m.Ndvs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Ndvs", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSelect(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSelect
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSelect(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSelect
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSelect
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSelect
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSelect
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSelect(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSelect = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSelect   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("select.proto", fileDescriptorSelect) }

var fileDescriptorSelect = []byte{
	// 1167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xee, 0xc6, 0x97, 0xd8, 0xc7, 0x97, 0x38, 0x93, 0xb4, 0xdd, 0x86, 0xe2, 0xba, 0x46, 0x50,
	0xd7, 0xaa, 0x9c, 0x52, 0x24, 0x2a, 0x1e, 0x00, 0xd5, 0xa9, 0x69, 0xa3, 0xb6, 0xb4, 0xda, 0x04,
	0x21, 0xf1, 0xb2, 0x9a, 0xec, 0x8e, 0xed, 0x51, 0x76, 0x67, 0xb6, 0x33, 0xe3, 0xc6, 0xe6, 0x0f,
	0xf0, 0xc8, 0x2b, 0xbf, 0x83, 0x5f, 0xd1, 0x47, 0x9e, 0x41, 0xaa, 0x50, 0xf9, 0x23, 0x68, 0x2e,
	0x9b, 0x38, 0x97, 0x8a, 0x22, 0x1e, 0x78, 0xf2, 0xec, 0xf7, 0x9d, 0x39, 0x33, 0xe7, 0xf2, 0x9d,
	0x31, 0xd4, 0x25, 0x49, 0x48, 0xa4, 0x06, 0x99, 0xe0, 0x8a, 0xa3, 0xa2, 0xa2, 0xd9, 0xc1, 0x56,
	0x93, 0xcc, 0x49, 0x34, 0x53, 0x5c, 0x58, 0x74, 0x6b, 0x73, 0xc2, 0x27, 0xdc, 0x2c, 0xb7, 0xf5,
	0xca, 0xa2, 0xdd, 0x4f, 0xa1, 0x10, 0xf0, 0x23, 0x74, 0x05, 0xca, 0x53, 0xcc, 0xe2, 0x84, 0xf8,
	0x5e, 0xc7, 0xeb, 0xd5, 0x03, 0xf7, 0x85, 0x10, 0x14, 0x63, 0xac, 0xb0, 0xbf, 0x62, 0x50, 0xb3,
	0xee, 0x7e, 0x01, 0xa5, 0x91, 0x10, 0x5c, 0x20, 0x1f, 0x8a, 0x11, 0x8f, 0xed, 0x96, 0xd2, 0xb0,
	0xf8, 0xfa, 0xcd, 0x8d, 0x4b, 0x81, 0x41, 0xd0, 0x15, 0x28, 0xa4, 0x72, 0x62, 0x76, 0x55, 0x1d,
	0xa1, 0x81, 0xee, 0x1c, 0xd0, 0x2e, 0x53, 0x44, 0xa4, 0x24, 0xa6, 0x58, 0x91, 0xe7, 0x33, 0x95,
	0xcd, 0x14, 0xba, 0x0f, 0x35, 0xc2, 0xf4, 0xbe, 0x50, 0x2d, 0x32, 0xeb, 0xae, 0x79, 0xaf, 0x35,
	0xd0, 0x51, 0x0c, 0x46, 0x86, 0xd8, 0x5f, 0x64, 0xc4, 0xf9, 0x01, 0x72, 0x8c, 0xa0, 0xdb, 0x50,
	0x8e, 0xa6, 0x33, 0x76, 0x28, 0xfd, 0x95, 0x4e, 0xa1, 0x57, 0xbb, 0x57, 0xb3, 0x7b, 0x76, 0x34,
	0xe6, 0xcc, 0x9d, 0x41, 0xf7, 0x8f, 0x02, 0x34, 0xf7, 0x4c, 0x92, 0x02, 0x22, 0x33, 0xce, 0x24,
	0x41, 0x37, 0xa1, 0x44, 0x74, 0x1c, 0xe6, 0xc0, 0xe3, 0xcd, 0x26, 0xb4, 0xc0, 0x32, 0xe8, 0x43,
	0x28, 0x0a, 0x7e, 0x94, 0xbb, 0xaf, 0x5a, 0x8b, 0x80, 0x1f, 0x05, 0x06, 0x5e, 0x3a, 0xbf, 0xf0,
	0x0f, 0xe7, 0xa3, 0x5b, 0x50, 0x39, 0xc2, 0x82, 0x51, 0x36, 0x91, 0x7e, 0x71, 0xd9, 0xd8, 0x9e,
	0x77, 0x4c, 0xa2, 0x8f, 0xa0, 0xc1, 0x4d, 0x5a, 0xc2, 0x88, 0xcf, 0x98, 0x92, 0x7e, 0xa9, 0x53,
	0xe8, 0x15, 0x82, 0xba, 0x05, 0x77, 0x0c, 0xa6, 0x8d, 0xdc, 0x06, 0x6b, 0xe5, 0x97, 0x3b, 0x9e,
	0x36, 0x72, 0xa0, 0xb1, 0x42, 0xcf, 0x61, 0xc3, 0xb6, 0x00, 0xe5, 0x2c, 0x94, 0xb3, 0x34, 0xc5,
	0x82, 0x12, 0xe9, 0x57, 0xcc, 0xe9, 0x6d, 0x77, 0xba, 0xeb, 0x91, 0x51, 0x6e, 0xb8, 0x67, 0xec,
	0x16, 0x01, 0x22, 0xa7, 0x11, 0x4a, 0xe4, 0xd9, 0x3a, 0x55, 0xdf, 0xbb, 0x4e, 0x08, 0x8a, 0x2c,
	0x7e, 0x25, 0x7d, 0x30, 0xa1, 0x98, 0x35, 0x7a, 0x02, 0x9b, 0x74, 0xa9, 0x15, 0x42, 0x1b, 0x9f,
	0xf4, 0x6b, 0xe6, 0x7a, 0xbe, 0xf5, 0x7a, 0xbe, 0x59, 0x82, 0x0d, 0x7a, 0x0e, 0x93, 0xdd, 0x9f,
	0x3d, 0x28, 0x99, 0xac, 0xa3, 0x7d, 0xa8, 0xea, 0xd2, 0x84, 0xa6, 0x6b, 0x0b, 0xba, 0x6b, 0x87,
	0xf7, 0xf5, 0x7d, 0x7e, 0x7f, 0x73, 0x63, 0x7b, 0x42, 0xd5, 0x74, 0x76, 0x30, 0x88, 0x78, 0xba,
	0x9d, 0x51, 0x36, 0x89, 0x70, 0xb6, 0xad, 0x4f, 0xd9, 0x96, 0x53, 0x2c, 0x48, 0x7c, 0xb0, 0x50,
	0x44, 0x0e, 0xf6, 0xcc, 0x7a, 0xa8, 0xd7, 0x41, 0x45, 0x7b, 0x7a, 0x88, 0x15, 0x46, 0x77, 0x9d,
	0xd7, 0x94, 0x28, 0xec, 0xca, 0xd7, 0x38, 0x6e, 0x86, 0x67, 0x44, 0x61, 0x17, 0xb4, 0xd9, 0xa1,
	0xbf, 0xbb, 0x87, 0x70, 0xed, 0xfc, 0xe5, 0x77, 0xa6, 0x98, 0x31, 0x92, 0xa0, 0x5b, 0x50, 0xcf,
	0xc5, 0x19, 0xd2, 0x78, 0xee, 0x7b, 0x9d, 0x95, 0x5e, 0xc3, 0xb9, 0xa8, 0xe5, 0xcc, 0x6e, 0x3c,
	0x47, 0x1f, 0x43, 0xd3, 0x35, 0x03, 0x1f, 0x8f, 0x25, 0x51, 0xb6, 0x13, 0x1b, 0x81, 0x6b, 0x91,
	0xe7, 0x16, 0xec, 0x8e, 0x60, 0xd5, 0xdd, 0x03, 0x5d, 0x3f, 0x25, 0xe4, 0x42, 0xde, 0x85, 0x4e,
	0xce, 0xd7, 0xa1, 0x9c, 0x10, 0x36, 0x51, 0x53, 0x23, 0xcd, 0x63, 0xd6, 0x62, 0xdd, 0x5f, 0x57,
	0x01, 0x1e, 0x3e, 0x78, 0x14, 0x90, 0x97, 0x33, 0x22, 0x15, 0xea, 0xc3, 0xba, 0x54, 0x58, 0xa8,
	0x50, 0xc9, 0x70, 0x8c, 0x93, 0xe4, 0x00, 0x47, 0x87, 0xc6, 0x6b, 0x31, 0x58, 0x33, 0xc4, 0xbe,
	0xfc, 0xc6, 0xc1, 0xe8, 0x0e, 0x54, 0xf3, 0x7b, 0xe7, 0x6a, 0x69, 0x9e, 0xee, 0xb0, 0xe0, 0xc4,
	0x00, 0x0d, 0xa0, 0xa5, 0x68, 0x4a, 0xc2, 0x1f, 0x39, 0x23, 0x2e, 0x32, 0x53, 0xab, 0xfc, 0x42,
	0x4d, 0xcd, 0xfe, 0xc0, 0x19, 0xb1, 0x01, 0xa2, 0x2d, 0x28, 0x8d, 0x13, 0x6c, 0x94, 0xe3, 0xf5,
	0x8a, 0xce, 0xc8, 0x42, 0x17, 0xa4, 0xa8, 0x74, 0x41, 0x8a, 0xd0, 0x5d, 0xd8, 0x8c, 0x78, 0xa2,
	0xf5, 0x1f, 0x0a, 0xcc, 0x26, 0x24, 0x57, 0x97, 0x16, 0x4e, 0x25, 0x40, 0x8e, 0x0b, 0x34, 0xe5,
	0x34, 0xd6, 0x87, 0xf5, 0x14, 0xcf, 0xc3, 0xd3, 0x3a, 0x5b, 0xb5, 0xe1, 0xa7, 0x78, 0xfe, 0xfd,
	0xb2, 0xd4, 0xce, 0x28, 0xa3, 0xf2, 0xde, 0xca, 0xb8, 0x06, 0x15, 0xf9, 0x32, 0x09, 0x53, 0x3d,
	0x46, 0xab, 0xc6, 0xf7, 0xaa, 0x7c, 0x99, 0x3c, 0xd3, 0x33, 0xb4, 0x0f, 0xcd, 0x93, 0x24, 0x31,
	0x9c, 0x12, 0xbf, 0xb6, 0x34, 0x4e, 0xeb, 0x79, 0x8a, 0xbe, 0xc5, 0x29, 0x41, 0x5f, 0xc1, 0x07,
	0x79, 0x74, 0x17, 0x49, 0xbe, 0x6e, 0x82, 0xbc, 0xe6, 0x4c, 0x46, 0xe7, 0x95, 0x7d, 0x07, 0x90,
	0x8e, 0x15, 0x27, 0x09, 0x3f, 0x22, 0x71, 0x98, 0xe1, 0xe8, 0x90, 0x28, 0xbf, 0x61, 0x2e, 0xd4,
	0x4a, 0xf1, 0xfc, 0x81, 0x25, 0x5e, 0x18, 0x1c, 0x3d, 0x82, 0x0d, 0x33, 0xd5, 0xc2, 0x94, 0xa4,
	0x5c, 0x2c, 0xc2, 0x04, 0x2f, 0xf8, 0x4c, 0xf9, 0x4d, 0x33, 0x46, 0xaf, 0x2e, 0xcd, 0xc0, 0x67,
	0x86, 0x7f, 0x6a, 0xe8, 0x60, 0x3d, 0x3a, 0x0b, 0xa1, 0x36, 0xd4, 0xa8, 0x0c, 0x45, 0xc6, 0x42,
	0x32, 0xcf, 0x84, 0xbf, 0x66, 0xae, 0x59, 0xa5, 0x32, 0xc8, 0xd8, 0x68, 0x9e, 0x09, 0xf4, 0x09,
	0x14, 0x67, 0x92, 0x08, 0xbf, 0x65, 0x3c, 0x23, 0xeb, 0xf9, 0x3b, 0x49, 0xc4, 0x6e, 0x4c, 0x98,
	0xa2, 0x6a, 0x11, 0x18, 0x1e, 0x7d, 0x06, 0x0d, 0xc1, 0x79, 0x1e, 0x3b, 0x17, 0xfe, 0xba, 0xd9,
	0x70, 0xb6, 0x03, 0xeb, 0xda, 0x28, 0xff, 0xd2, 0xf5, 0x1d, 0x73, 0x11, 0x91, 0x70, 0xb9, 0x72,
	0xc8, 0x5c, 0x61, 0xcd, 0x10, 0x27, 0x85, 0x43, 0x9f, 0xc3, 0xd5, 0x98, 0xbe, 0x0a, 0x33, 0x41,
	0x22, 0x2a, 0x75, 0x6e, 0x29, 0x8b, 0x04, 0x49, 0x09, 0x53, 0xfe, 0x46, 0xc7, 0xeb, 0x35, 0x82,
	0xcb, 0x31, 0x7d, 0xf5, 0x22, 0x67, 0x77, 0x73, 0x12, 0x61, 0xb8, 0x7e, 0xc1, 0x90, 0x0b, 0x23,
	0x3b, 0x07, 0xa4, 0xbf, 0x69, 0x94, 0x72, 0xe3, 0x5d, 0xc3, 0xce, 0xcd, 0x8b, 0x60, 0x8b, 0xbe,
	0x8b, 0x92, 0xdd, 0xaf, 0x61, 0xfd, 0x5c, 0xae, 0x51, 0x1f, 0xca, 0x84, 0xc5, 0x14, 0x33, 0xf7,
	0x98, 0xd6, 0xf3, 0x56, 0xd4, 0x58, 0xae, 0x7a, 0x6b, 0xd1, 0xdd, 0x87, 0xfa, 0x72, 0x4a, 0xd1,
	0x4d, 0xa8, 0xea, 0xa4, 0xda, 0x96, 0xf3, 0x96, 0x5a, 0xae, 0xa2, 0x61, 0xd3, 0x6e, 0xb9, 0xc9,
	0x94, 0x4b, 0x75, 0xea, 0x91, 0x37, 0x26, 0x8f, 0xb9, 0x54, 0xdd, 0x9f, 0x56, 0xa0, 0xb9, 0xa7,
	0x04, 0xc1, 0xe9, 0xbf, 0x79, 0x6f, 0x9f, 0xb8, 0xbf, 0x1b, 0xff, 0x71, 0x70, 0x1b, 0x27, 0xff,
	0xc7, 0x93, 0x9b, 0x3f, 0x74, 0xab, 0x27, 0x0f, 0x5d, 0xff, 0x4b, 0x80, 0xa5, 0x4e, 0x5a, 0x83,
	0x9a, 0xfe, 0x7d, 0x48, 0xc6, 0x78, 0x96, 0xa8, 0xd6, 0x25, 0xd4, 0x80, 0xaa, 0x06, 0x4c, 0x0d,
	0x5b, 0x5e, 0xce, 0xef, 0x3c, 0x1e, 0x26, 0x3c, 0x3a, 0x6c, 0xad, 0xf4, 0x6f, 0x43, 0xd9, 0x96,
	0x0d, 0xb5, 0xa0, 0xfe, 0x94, 0x2a, 0x95, 0x10, 0xfb, 0x6d, 0xf7, 0x0e, 0xe9, 0xc4, 0x7d, 0x7a,
	0xc3, 0xdb, 0xaf, 0xdf, 0xb6, 0xbd, 0xdf, 0xde, 0xb6, 0xbd, 0x3f, 0xdf, 0xb6, 0xbd, 0x5f, 0xfe,
	0x6a, 0x5f, 0x82, 0xcb, 0x11, 0x4f, 0x07, 0x2e, 0x65, 0x03, 0x45, 0xe3, 0x03, 0x93, 0x80, 0x17,
	0xde, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x7c, 0xb9, 0xb0, 0x31, 0x0a, 0x00, 0x00,
}
