// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spfresh_teardown.proto

package tipb

import (
	"fmt"
	"io"
	"math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"

	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SPFreshTeardownRequest struct {
	KeyspaceId uint32 `protobuf:"varint,1,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	TableId    int64  `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	IndexId    int64  `protobuf:"varint,3,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
}

func (m *SPFreshTeardownRequest) Reset()         { *m = SPFreshTeardownRequest{} }
func (m *SPFreshTeardownRequest) String() string { return proto.CompactTextString(m) }
func (*SPFreshTeardownRequest) ProtoMessage()    {}
func (*SPFreshTeardownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c300fd4e75fe3c, []int{0}
}
func (m *SPFreshTeardownRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPFreshTeardownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPFreshTeardownRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPFreshTeardownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPFreshTeardownRequest.Merge(m, src)
}
func (m *SPFreshTeardownRequest) XXX_Size() int {
	return m.Size()
}
func (m *SPFreshTeardownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SPFreshTeardownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SPFreshTeardownRequest proto.InternalMessageInfo

func (m *SPFreshTeardownRequest) GetKeyspaceId() uint32 {
	if m != nil {
		return m.KeyspaceId
	}
	return 0
}

func (m *SPFreshTeardownRequest) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *SPFreshTeardownRequest) GetIndexId() int64 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func init() {
	proto.RegisterType((*SPFreshTeardownRequest)(nil), "tipb.SPFreshTeardownRequest")
}

func init() { proto.RegisterFile("spfresh_teardown.proto", fileDescriptor_c4c300fd4e75fe3c) }

var fileDescriptor_c4c300fd4e75fe3c = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x48, 0x2b,
	0x4a, 0x2d, 0xce, 0x88, 0x2f, 0x49, 0x4d, 0x2c, 0x4a, 0xc9, 0x2f, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x29, 0xc9, 0x2c, 0x48, 0x92, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x0b,
	0xe8, 0x83, 0x58, 0x10, 0x39, 0x29, 0xfe, 0xa2, 0xd2, 0xe2, 0x12, 0x30, 0x13, 0x22, 0xa0, 0x94,
	0xcf, 0x25, 0x16, 0x1c, 0xe0, 0x06, 0x32, 0x26, 0x04, 0x6a, 0x4a, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x90, 0x3c, 0x17, 0x77, 0x76, 0x6a, 0x65, 0x71, 0x41, 0x62, 0x72, 0x6a, 0x7c, 0x66,
	0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x17, 0x4c, 0xc8, 0x33, 0x45, 0x48, 0x92, 0x8b,
	0xa3, 0x24, 0x31, 0x29, 0x07, 0x2c, 0xcb, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x0e, 0xe6, 0x43,
	0xa4, 0x32, 0xf3, 0x52, 0x52, 0x2b, 0x40, 0x52, 0xcc, 0x10, 0x29, 0x30, 0xdf, 0x33, 0xc5, 0xc9,
	0xf2, 0xc6, 0x0a, 0x0e, 0xc6, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48,
	0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x19, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1,
	0x58, 0x8e, 0x81, 0x4b, 0x34, 0x39, 0x3f, 0x57, 0xaf, 0x20, 0x33, 0x2f, 0x3d, 0x39, 0xb1, 0x40,
	0xaf, 0x24, 0x33, 0x25, 0x49, 0x0f, 0xe4, 0xa1, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0x93, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x61, 0x19, 0xbf, 0xf9, 0x00, 0x00, 0x00,
}

func (m *SPFreshTeardownRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPFreshTeardownRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPFreshTeardownRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IndexId != 0 {
		i = encodeVarintSpfreshTeardown(dAtA, i, uint64(m.IndexId))
		i--
		dAtA[i] = 0x18
	}
	if m.TableId != 0 {
		i = encodeVarintSpfreshTeardown(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x10
	}
	if m.KeyspaceId != 0 {
		i = encodeVarintSpfreshTeardown(dAtA, i, uint64(m.KeyspaceId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSpfreshTeardown(dAtA []byte, offset int, v uint64) int {
	offset -= sovSpfreshTeardown(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SPFreshTeardownRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeyspaceId != 0 {
		n += 1 + sovSpfreshTeardown(uint64(m.KeyspaceId))
	}
	if m.TableId != 0 {
		n += 1 + sovSpfreshTeardown(uint64(m.TableId))
	}
	if m.IndexId != 0 {
		n += 1 + sovSpfreshTeardown(uint64(m.IndexId))
	}
	return n
}

func sovSpfreshTeardown(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSpfreshTeardown(x uint64) (n int) {
	return sovSpfreshTeardown(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SPFreshTeardownRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpfreshTeardown
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPFreshTeardownRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPFreshTeardownRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyspaceId", wireType)
			}
			m.KeyspaceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfreshTeardown
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyspaceId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfreshTeardown
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			m.IndexId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpfreshTeardown
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpfreshTeardown(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpfreshTeardown
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSpfreshTeardown(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSpfreshTeardown
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpfreshTeardown
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpfreshTeardown
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSpfreshTeardown
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSpfreshTeardown
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSpfreshTeardown
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSpfreshTeardown        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSpfreshTeardown          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSpfreshTeardown = fmt.Errorf("proto: unexpected end of group")
)
